class CocoUrduLabels {
  const CocoUrduLabels._();

  /// Maps English COCO label to natural, conversational Pakistani Urdu term.
  static const Map<String, String> translations = {
    'person': 'انسان',
    'bicycle': 'سائیکل',
    'car': 'گاڑی',
    'motorcycle': 'موٹر سائیکل',
    'airplane': 'ہوائی جہاز',
    'bus': 'بس',
    'train': 'ریل گاڑی',
    'truck': 'ٹرک',
    'boat': 'کشتی',
    'traffic light': 'ٹریفک اشارہ',
    'fire hydrant': 'فائر ہائیڈرنٹ',
    'stop sign': 'رکنے کا بورڈ',
    'parking meter': 'پارکنگ میٹر',
    'bench': 'بینچ',
    'bird': 'پرندہ',
    'cat': 'بلی',
    'dog': 'کتا',
    'horse': 'گھوڑا',
    'sheep': 'بھیڑ',
    'cow': 'گائے',
    'elephant': 'ہاتھی',
    'bear': 'ریچھ',
    'zebra': 'زیبرا',
    'giraffe': 'زرافہ',
    'backpack': 'بستہ',
    'umbrella': 'چھتری',
    'handbag': 'ہینڈ بیگ',
    'tie': 'ٹائی',
    'suitcase': 'سوٹ کیس',
    'frisbee': 'فرس بی',
    'skis': 'سکیز',
    'snowboard': 'سنو بورڈ',
    'sports ball': 'گیند',
    'kite': 'پتنگ',
    'baseball bat': 'بیٹ',
    'baseball glove': 'دستانہ',
    'skateboard': 'سکیٹ بورڈ',
    'surfboard': 'سرف بورڈ',
    'tennis racket': 'ریکیٹ',
    'bottle': 'بوتل',
    'wine glass': 'شیشے کا گلاس',
    'cup': 'کپ',
    'fork': 'کانٹا',
    'knife': 'چھری',
    'spoon': 'چمچ',
    'bowl': 'پیالہ',
    'banana': 'کیلا',
    'apple': 'سیب',
    'sandwich': 'سینڈوچ',
    'orange': 'مالٹا',
    'broccoli': 'بروکلی',
    'carrot': 'گاجر',
    'hot dog': 'ہاٹ ڈاگ',
    'pizza': 'پیزا',
    'donut': 'ڈونٹ',
    'cake': 'کیک',
    'chair': 'کرسی',
    'couch': 'صوفہ',
    'potted plant': 'گملے میں پودا',
    'bed': 'بستر',
    'dining table': 'میز',
    'toilet': 'باتھ روم',
    'tv': 'ٹی وی',
    'laptop': 'لیپ ٹاپ',
    'mouse': 'کمپیوٹر ماؤس',
    'remote': 'ریموٹ',
    'keyboard': 'کی بورڈ',
    'cell phone': 'موبائل فون',
    'microwave': 'مائیکرو ویو',
    'oven': 'اوون',
    'toaster': 'ٹوسٹر',
    'sink': 'بیسن',
    'refrigerator': 'فریج',
    'book': 'کتاب',
    'clock': 'گھڑی',
    'vase': 'گلدان',
    'scissors': 'قینچی',
    'teddy bear': 'کھلونا',
    'hair drier': 'ہیئر ڈرائر',
    'toothbrush': 'توتھ برش',
  };

  /// Returns the Urdu translation for an English COCO label, falling back to the original label if not found.
  static String translate(String englishLabel) {
    return translations[englishLabel.toLowerCase()] ?? englishLabel;
  }
}
